In [ ]:
import torch


In [1]:
pip install d2l==0.17.5

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.4/82.4 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 31.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 76.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 105.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 25.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 19.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.5/93.5 kB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.

# 新段落

In [32]:
import torch
from torch import nn
from IPython import display
from d2l import torch as d2l
import numpy as np
import pandas as pd
import os

In [13]:
x=torch.arange(12,dtype=torch.float32)
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
torch.zeros(12).reshape(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
x=torch.tensor([[2,3],[3,4]])##中括号套中括号
z=torch.ones_like(x) ###创建和已知矩阵相同shape的全为0或1的矩阵
x,z

(tensor([[2, 3],
         [3, 4]]),
 tensor([[1, 1],
         [1, 1]]))

In [20]:
y=torch.arange(4).reshape(2,2)
x=torch.tensor([[2,3],[3,4]])
z=torch.cat((x,y),dim=0)##cat拼接，记得括号，dim=0:上下拼接，dim=1：左右拼接
z

tensor([[2, 3],
        [3, 4],
        [0, 1],
        [2, 3]])

In [23]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X, X[1:3],X[-1],X[2,3]   ##索引从0开始 1：3 实际上是1，2 不包含3 即第2，3行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor(11.))

In [24]:
X[0:1]=12#把第一行变成12
X

tensor([[12., 12., 12., 12.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

和numpy转换

In [28]:
a = torch.tensor([3.5])
# Transformation between value and vector
a, a.item()  ##如何取出张量的值
# Transformation between different data types
float(a), int(a)

(3.5, 3)

In [31]:
a = np.ones(5)
b = torch.from_numpy(a)  #利用torch.from_numpy从Numpy得到tensor
type(a), type(b)

(numpy.ndarray, torch.Tensor)

联动pandas 涉及如何填充缺失值（数值和分类变量）以及df变tensor

In [33]:
import os
# "./" means the current folder
# ./data
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
# ./data/house_tiny.csv
data_file = os.path.join('.', 'data', 'house_tiny.csv')
# NA means missing data
with open(data_file, 'w') as f:
    f.write('NumRooms,Viewed,Alley,Price\n')  # Column names
    f.write('NA,3,Pave,127500\n')  # Each row represents a data example
    f.write('2,3,NA,106000\n')
    f.write('4,NA,NA,178100\n')
    f.write('NA,3,NA,140000\n')

In [34]:
# If pandas is not installed, just uncomment the following line:
# !pip install pandas

# pandas is usually used for data loading and processing
import pandas as pd

data = pd.read_csv(data_file)
# NaN means missing data
print(data)

   NumRooms  Viewed Alley   Price
0       NaN     3.0  Pave  127500
1       2.0     3.0   NaN  106000
2       4.0     NaN   NaN  178100
3       NaN     3.0   NaN  140000


In [35]:
a,b=data.iloc[:,:2],data.iloc[:,2:]
a,b

(   NumRooms  Viewed
 0       NaN     3.0
 1       2.0     3.0
 2       4.0     NaN
 3       NaN     3.0,
   Alley   Price
 0  Pave  127500
 1   NaN  106000
 2   NaN  178100
 3   NaN  140000)

In [38]:
##填充缺失值
a=a.fillna(a.mean())  ##a=a.fillna(a.mean())
#离散型变量 将nan视为一个新的变量，one-hot编码成为两列 pd.get_dummies获取one-hot编码
b=pd.get_dummies(b,dummy_na=True) ##dummy_na=Ture:表示会将nan视为一种分类，否则默认忽略
a,b

(   NumRooms  Viewed
 0       3.0     3.0
 1       2.0     3.0
 2       4.0     3.0
 3       3.0     3.0,
     Price  Alley_Pave  Alley_nan
 0  127500           1          0
 1  106000           0          1
 2  178100           0          1
 3  140000           0          1)

pandas到torch  .values

In [40]:
X,y=torch.tensor(a.values),torch.tensor(b.values.astype(int))
X,y

(tensor([[3., 3.],
         [2., 3.],
         [4., 3.],
         [3., 3.]], dtype=torch.float64),
 tensor([[127500,      1,      0],
         [106000,      0,      1],
         [178100,      0,      1],
         [140000,      0,      1]]))

In [41]:
type(X)

torch.Tensor